[package]
authors = ["Aaron Trent <novacrazy@gmail.com>"]
name = "softrender"
description = "Software Renderer in Rust"
version = "0.1.0"
license = "MIT"
repository = "https://github.com/novacrazy/rust-softrender"
readme = "README.md"
keywords = ["render", "renderer", "rasterizer", "3d"]
documentation = "https://docs.rs/softrender/"
include = ["src/**/*", "Cargo.toml"]

[dependencies]
nalgebra = "0.12"
rayon = "0.7.0"

[dependencies.image]
optional = true
version = "0.13"

[dev-dependencies]
image = "0.13.0"
tobj = "0.1.3"

[features]
default = []
image_compat = ["image"]
