[package]
authors = ["Aaron Trent <novacrazy@gmail.com>"]
name = "softrender"
version = "0.1.0"

[dependencies]
nalgebra = "0.12"
rayon = "0.7.0"

[dependencies.image]
optional = true
version = "0.13"

[dev-dependencies]
image = "0.13.0"
tobj = "0.1.3"

[features]
default = []
image_compat = ["image"]
