[package]
authors = ["Aaron Trent <novacrazy@gmail.com>"]
name = "softrender"
version = "0.1.0"

[dependencies]
nalgebra = "0.12"
rayon = "0.7.0"

[dependencies.image]
optional = true
version = "0.13"

[features]
default = []
image_compat = ["image"]
